language: java

addons: 
    sonarcloud:
        organization: "Mikekim3"

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.organization=Mikekim3-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=e560c2ef91c36bf167460a1c4f000f35d05886af -Dsonar.projectKey=com.ipi.java.340 -Dsonar.branch=master